services:
  - type: web
    name: nyeri-stays-frontend
    env: node
    buildCommand: |
      cd "frontend/Nyeri Stays"
      npm install
      npm run build
    startCommand: cd "frontend/Nyeri Stays" && node server.js
    envVars:
      - key: VITE_API_BASE_URL
        value: https://nyeristays.onrender.com/api
      - key: VITE_BACKEND_URL
        value: https://nyeristays.onrender.com
      - key: VITE_FRONTEND_URL
        value: https://nyeri-stays.onrender.com
