services:
  - type: web
    name: nyeristays-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        value: nyeristays@gmail.com
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
