services:
  - type: web
    name: nyeri-stays-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://nyeristays.onrender.com/api
      - key: VITE_BACKEND_URL
        value: https://nyeristays.onrender.com
      - key: VITE_FRONTEND_URL
        value: https://nyeri-stays-frontend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
